
package com.punit.entities;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import jakarta.persistence.*;

@Entity
@Table(name = "SALESORDER_ITEM")
public class SalesOrderItem {

    // ✅ itemNumber is the @Id — auto-generated by DB, unique, never repeats
    //    No soItemId, no salesOrderNumber-as-PK — clean and simple
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ITEM_NUMBER", nullable = false)
    private Integer itemNumber;

    @Column(name = "MATERIAL")
    private String material;

    @Column(name = "QUANTITY")
    private Integer quantity;

    @Column(name = "UOM")
    private String uom;

    // ✅ @ManyToOne — multiple items can belong to one SO Header
    //    Was @OneToOne which wrongly blocked more than one item per order
	/* @JsonIgnoreProperties("items") */
    @JsonIgnoreProperties({"dateOfOrder", "dateOfDelivery", "customer", "items"})
    @ManyToOne
    @JoinColumn(name = "SO_NUMBER", nullable = false)
    private SalesOrderHeader salesOrderHeader;

    public SalesOrderItem() {}

    public SalesOrderItem(Integer itemNumber, String material,
                          Integer quantity, String uom,
                          SalesOrderHeader salesOrderHeader) {
        this.itemNumber       = itemNumber;
        this.material         = material;
        this.quantity         = quantity;
        this.uom              = uom;
        this.salesOrderHeader = salesOrderHeader;
    }

    public Integer getItemNumber() { return itemNumber; }
    public void setItemNumber(Integer itemNumber) { this.itemNumber = itemNumber; }

    public String getMaterial() { return material; }
    public void setMaterial(String material) { this.material = material; }

    public Integer getQuantity() { return quantity; }
    public void setQuantity(Integer quantity) { this.quantity = quantity; }

    public String getUom() { return uom; }
    public void setUom(String uom) { this.uom = uom; }

    public SalesOrderHeader getSalesOrderHeader() { return salesOrderHeader; }

    // ✅ Renamed setSalesOrder() → setSalesOrderHeader() — matches getter name
    public void setSalesOrderHeader(SalesOrderHeader salesOrderHeader) {
        this.salesOrderHeader = salesOrderHeader;
    }
}