### PostgreSQL Database Configuration (Cloud Foundry)
#spring.datasource.url=jdbc:postgresql://ep-icy-pine-a1f3l52v-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_QBe9mfPKs3oJ
#spring.datasource.driver-class-name=org.postgresql.Driver
#
### Connection Pool Configuration
#spring.datasource.hikari.connectionTimeout=20000
#spring.datasource.hikari.maximumPoolSize=5
#spring.datasource.hikari.minimumIdle=1
#spring.datasource.hikari.idleTimeout=300000
#spring.datasource.hikari.maxLifetime=1200000
#
### JPA/Hibernate Configuration
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.id.db_structure_naming_strategy=single
#spring.jpa.properties.hibernate.jdbc.batch_size=20
#spring.jpa.properties.hibernate.order_inserts=true
#spring.jpa.properties.hibernate.order_updates=true
#spring.jpa.hibernate.ddl-auto=update




## default connection pool
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

## PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Puneet@2001

# create and drop table, good for testing, production set to none or comment it
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update










